In [2]:
# setting random state for reproducibility
random_state = 22

# import libraries
import pandas as pd

The datasets provided for this projects are too large. 

To avoid problems as we develop the project, I've decided to take a sample of both datasets to work with.

These are the two data files that will be handled in this notebook:

- `Udacity_AZDIAS_052018.csv`: Demographics data for the general population of Germany; 891 211 persons (rows) x 366 features (columns).
- `Udacity_CUSTOMERS_052018.csv`: Demographics data for customers of a mail-order company; 191 652 persons (rows) x 369 features (columns).

In [3]:
# load in the data
azdias_full = pd.read_csv('data/Udacity_AZDIAS_052018.csv', sep=';')
customers_full = pd.read_csv('data/Udacity_CUSTOMERS_052018.csv', sep=';')

C:\Users\Qesh\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [4]:
# check the datasets sizes
print('AZDIAS:     ',azdias_full.shape)
print('CUSTOMERS:  ',customers_full.shape)

AZDIAS:      (891221, 366)
CUSTOMERS:   (191652, 369)


In [5]:
azdias_full.head()

LNR  AGER_TYP  AKT_DAT_KL  ALTER_HH  ALTER_KIND1  ALTER_KIND2  \
0  910215        -1         NaN       NaN          NaN          NaN   
1  910220        -1         9.0       0.0          NaN          NaN   
2  910225        -1         9.0      17.0          NaN          NaN   
3  910226         2         1.0      13.0          NaN          NaN   
4  910241        -1         1.0      20.0          NaN          NaN   

   ALTER_KIND3  ALTER_KIND4  ALTERSKATEGORIE_FEIN  ANZ_HAUSHALTE_AKTIV  ...  \
0          NaN          NaN                   NaN                  NaN  ...   
1          NaN          NaN                  21.0                 11.0  ...   
2          NaN          NaN                  17.0                 10.0  ...   
3          NaN          NaN                  13.0                  1.0  ...   
4          NaN          NaN                  14.0                  3.0  ...   

   VHN  VK_DHT4A  VK_DISTANZ  VK_ZG11  W_KEIT_KIND_HH  WOHNDAUER_2008  \
0  NaN       NaN         NaN      NaN             NaN             NaN   
1  4.0       8.0        11.0     10.0             3.0             9.0   
2  2.0       9.0         9.0      6.0             3.0             9.0   
3  0.0       7.0        10.0     11.0             NaN             9.0   
4  2.0       3.0         5.0      4.0             2.0             9.0   

   WOHNLAGE ZABEOTYP ANREDE_KZ ALTERSKATEGORIE_GROB  
0       NaN        3         1                    2  
1       4.0        5         2                    1  
2       2.0        5         2                    3  
3       7.0        3         2                    4  
4       3.0        4         1                    3  

[5 rows x 366 columns]

In [6]:
customers_full.head()

LNR  AGER_TYP  AKT_DAT_KL  ALTER_HH  ALTER_KIND1  ALTER_KIND2  \
0    9626         2         1.0      10.0          NaN          NaN   
1    9628        -1         9.0      11.0          NaN          NaN   
2  143872        -1         1.0       6.0          NaN          NaN   
3  143873         1         1.0       8.0          NaN          NaN   
4  143874        -1         1.0      20.0          NaN          NaN   

   ALTER_KIND3  ALTER_KIND4  ALTERSKATEGORIE_FEIN  ANZ_HAUSHALTE_AKTIV  ...  \
0          NaN          NaN                  10.0                  1.0  ...   
1          NaN          NaN                   NaN                  NaN  ...   
2          NaN          NaN                   0.0                  1.0  ...   
3          NaN          NaN                   8.0                  0.0  ...   
4          NaN          NaN                  14.0                  7.0  ...   

   VK_ZG11  W_KEIT_KIND_HH  WOHNDAUER_2008  WOHNLAGE  ZABEOTYP  \
0      2.0             6.0             9.0       7.0         3   
1      3.0             0.0             9.0       NaN         3   
2     11.0             6.0             9.0       2.0         3   
3      2.0             NaN             9.0       7.0         1   
4      4.0             2.0             9.0       3.0         1   

       PRODUCT_GROUP  CUSTOMER_GROUP ONLINE_PURCHASE ANREDE_KZ  \
0  COSMETIC_AND_FOOD     MULTI_BUYER               0         1   
1               FOOD    SINGLE_BUYER               0         1   
2  COSMETIC_AND_FOOD     MULTI_BUYER               0         2   
3           COSMETIC     MULTI_BUYER               0         1   
4               FOOD     MULTI_BUYER               0         1   

  ALTERSKATEGORIE_GROB  
0                    4  
1                    4  
2                    4  
3                    4  
4                    3  

[5 rows x 369 columns]

Let's go ahead and do a random sampling of 25% of the datasets with no replacing.

In [7]:
azdias = azdias_full.sample(frac=0.25, replace=False, random_state=random_state)
customers = customers_full.sample(frac=0.25, replace=False, random_state=random_state)

print(f'Rows of full AZDIAS dataset:      {azdias_full.shape[0]}\nRows of sample AZDIAS dataset:    {azdias.shape[0]}\n')
print(f'Rows of full CUSTOMERS dataset:   {customers_full.shape[0]}\nRows of sample CUSTOMERS dataset: {customers.shape[0]}')

Rows of full AZDIAS dataset:      891221
Rows of sample AZDIAS dataset:    222805

Rows of full CUSTOMERS dataset:   191652
Rows of sample CUSTOMERS dataset: 47913


We should now have these two files to go ahead with the project:

- `sample_AZDIAS.csv`: Demographics data for the general population of Germany; 222 805 persons (rows) x 366 features (columns).
- `sample_CUSTOMERS.csv`: Demographics data for customers of a mail-order company; 47 913 persons (rows) x 369 features (columns).

In [12]:
# exporting sample files to csv
azdias.to_csv('data/sample_AZDIAS.csv')
customers.to_csv('data/sample_CUSTOMERS.csv')

print('\n----> Sample datasets were exported successfully!')


----> Sample datasets were exported successfully!
